# Generated by Django 3.0.5 on 2023-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], max_length=10, null=True),
        ),
    ]
