# Generated by Django 3.0.5 on 2023-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('one', 'one'), ('two', 'two'), ('three', 'three')], max_length=10, null=True),
        ),
    ]
